const fs = require('fs');
let content = fs.readFileSync('src/components/ImmersiveWorkout.jsx', 'utf8');
content = content.replace(/flex flex-col   overflow-hidden/g, 'flex flex-col ${t.bgApp} ${t.textMain} overflow-hidden');
content = content.replace(/uppercase  tracking-widest/g, 'uppercase ${t.textMuted} tracking-widest');
content = content.replace(/font-black \">\{formatTime/g, 'font-black ${t.textAccent}\">{formatTime');
content = content.replace(/className=\"\" \/>/g, 'className={`${t.textAccent}`} />');
content = content.replace(/rounded-full  hover:opacity-80/g, 'rounded-full ${t.bgAccent} hover:opacity-80');
content = content.replace(/bg-zinc-900/g, '${t.bgCard}');
content = content.replace(/bg-black\/50 text-white/g, '${t.bgCard} opacity-90 ${t.textMain}');
content = content.replace(/bg-black\/60 backdrop-blur-md p-2 rounded-xl text-white\/80 hover:text-white/g, '${t.bgCard} opacity-90 backdrop-blur-md p-2 rounded-xl ${t.textMuted} hover:${t.textMain}');
content = content.replace(/text-white\/10/g, 'opacity-10');
content = content.replace(/text-white\/20/g, 'opacity-20');
content = content.replace(/bg-white\/10/g, 'bg-black/10 dark:bg-white/10');
content = content.replace(/bg-white\/20/g, 'bg-black/20 dark:bg-white/20');
content = content.replace(/text-white\/50/g, '${t.textMuted}');
content = content.replace(/text-white\/70/g, '${t.textMuted}');
content = content.replace(/text-white/g, '${t.textMain}');
content = content.replace(/bg-black/g, '${t.bgApp}');
fs.writeFileSync('src/components/ImmersiveWorkout.jsx', content);
