/* tslint:disable */
/* eslint-disable */
/**
 * ExerciseDB API
 * # Introduction             ExerciseDB API, accessible at [exercisedb-api.vercel.app](https://exercisedb-api.vercel.app), is an exercises API that allows users to access high-quality exercises data which consists 1300+ exercises.           This API offers extensive information on each exercise, including target body parts, equipment needed, GIFs for visual guidance, and step-by-step instructions. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * new access token
 * @export
 * @interface AccessToken
 */
export interface AccessToken {
    /**
     * access token for making post requests
     * @type {string}
     * @memberof AccessToken
     */
    'accessToken': string;
}
/**
 * 
 * @export
 * @interface AuthenticateUser200Response
 */
export interface AuthenticateUser200Response {
    /**
     * Indicates whether the authentication request was successful
     * @type {boolean}
     * @memberof AuthenticateUser200Response
     */
    'success': boolean;
    /**
     * 
     * @type {AccessToken}
     * @memberof AuthenticateUser200Response
     */
    'data': AccessToken;
}
/**
 * 
 * @export
 * @interface AuthenticateUserRequest
 */
export interface AuthenticateUserRequest {
    /**
     * user registered email address
     * @type {string}
     * @memberof AuthenticateUserRequest
     */
    'email': string;
    /**
     * code generated by Authenticator app 
     * @type {string}
     * @memberof AuthenticateUserRequest
     */
    'code': string;
}
/**
 * 
 * @export
 * @interface AutocompleteExercises200Response
 */
export interface AutocompleteExercises200Response {
    /**
     * Indicates whether the request was successful.
     * @type {boolean}
     * @memberof AutocompleteExercises200Response
     */
    'success': boolean;
    /**
     * Array of suggested exercise names based on the search term.
     * @type {Array<string>}
     * @memberof AutocompleteExercises200Response
     */
    'data': Array<string>;
}
/**
 * 
 * @export
 * @interface CreateEquipment201Response
 */
export interface CreateEquipment201Response {
    /**
     * Indicates whether the request was successful
     * @type {boolean}
     * @memberof CreateEquipment201Response
     */
    'success': boolean;
    /**
     * The newly added equipment data
     * @type {Array<GetMusclesGet200ResponseDataInner>}
     * @memberof CreateEquipment201Response
     */
    'data': Array<GetMusclesGet200ResponseDataInner>;
}
/**
 * 
 * @export
 * @interface CreateEquipmentRequest
 */
export interface CreateEquipmentRequest {
    /**
     * The name of the equipment to be added
     * @type {string}
     * @memberof CreateEquipmentRequest
     */
    'name': string;
}
/**
 * 
 * @export
 * @interface CreateExercise201Response
 */
export interface CreateExercise201Response {
    /**
     * Indicates whether the exercise was successfully added to the database.
     * @type {boolean}
     * @memberof CreateExercise201Response
     */
    'success': boolean;
    /**
     * Details of the newly added exercise, including relevant information.
     * @type {Array<GetExercises200ResponseDataInner>}
     * @memberof CreateExercise201Response
     */
    'data': Array<GetExercises200ResponseDataInner>;
}
/**
 * 
 * @export
 * @interface CreateExercise400Response
 */
export interface CreateExercise400Response {
    /**
     * 
     * @type {boolean}
     * @memberof CreateExercise400Response
     */
    'success': boolean;
    /**
     * 
     * @type {string}
     * @memberof CreateExercise400Response
     */
    'error': string;
}
/**
 * 
 * @export
 * @interface CreateExerciseRequest
 */
export interface CreateExerciseRequest {
    /**
     * Unique identifier for the exercise.
     * @type {string}
     * @memberof CreateExerciseRequest
     */
    'exerciseId': string;
    /**
     * The name of the exercise.
     * @type {string}
     * @memberof CreateExerciseRequest
     */
    'name': string;
    /**
     * URL of the GIF demonstrating the exercise.
     * @type {string}
     * @memberof CreateExerciseRequest
     */
    'gifUrl': string;
    /**
     * Primary muscles targeted by the exercise.
     * @type {Array<string>}
     * @memberof CreateExerciseRequest
     */
    'targetMuscles': Array<string>;
    /**
     * Body parts involved in the exercise.
     * @type {Array<string>}
     * @memberof CreateExerciseRequest
     */
    'bodyParts': Array<string>;
    /**
     * Equipment required to perform the exercise.
     * @type {Array<string>}
     * @memberof CreateExerciseRequest
     */
    'equipments': Array<string>;
    /**
     * Secondary muscles that are worked during the exercise.
     * @type {Array<string>}
     * @memberof CreateExerciseRequest
     */
    'secondaryMuscles': Array<string>;
    /**
     * Step-by-step instructions to perform the exercise.
     * @type {Array<string>}
     * @memberof CreateExerciseRequest
     */
    'instructions': Array<string>;
}
/**
 * 
 * @export
 * @interface CreateMuscle201Response
 */
export interface CreateMuscle201Response {
    /**
     * Indicates whether the request was successful
     * @type {boolean}
     * @memberof CreateMuscle201Response
     */
    'success': boolean;
    /**
     * The newly added muscle data
     * @type {Array<GetMusclesGet200ResponseDataInner>}
     * @memberof CreateMuscle201Response
     */
    'data': Array<GetMusclesGet200ResponseDataInner>;
}
/**
 * 
 * @export
 * @interface CreateMuscleRequest
 */
export interface CreateMuscleRequest {
    /**
     * The name of the muscle to be added
     * @type {string}
     * @memberof CreateMuscleRequest
     */
    'name': string;
}
/**
 * 
 * @export
 * @interface CreatebodyPart201Response
 */
export interface CreatebodyPart201Response {
    /**
     * Indicates whether the request was successful
     * @type {boolean}
     * @memberof CreatebodyPart201Response
     */
    'success': boolean;
    /**
     * The newly added bodyPart data
     * @type {Array<GetMusclesGet200ResponseDataInner>}
     * @memberof CreatebodyPart201Response
     */
    'data': Array<GetMusclesGet200ResponseDataInner>;
}
/**
 * 
 * @export
 * @interface CreatebodyPartRequest
 */
export interface CreatebodyPartRequest {
    /**
     * The name of the bodyPart to be added
     * @type {string}
     * @memberof CreatebodyPartRequest
     */
    'name': string;
}
/**
 * 
 * @export
 * @interface GetBodyParts200Response
 */
export interface GetBodyParts200Response {
    /**
     * Indicates whether the request was successful
     * @type {boolean}
     * @memberof GetBodyParts200Response
     */
    'success': boolean;
    /**
     * Array of bodyparts.
     * @type {Array<GetMusclesGet200ResponseDataInner>}
     * @memberof GetBodyParts200Response
     */
    'data': Array<GetMusclesGet200ResponseDataInner>;
}
/**
 * 
 * @export
 * @interface GetEquipments200Response
 */
export interface GetEquipments200Response {
    /**
     * Indicates whether the request was successful
     * @type {boolean}
     * @memberof GetEquipments200Response
     */
    'success': boolean;
    /**
     * Array of equipments.
     * @type {Array<GetMusclesGet200ResponseDataInner>}
     * @memberof GetEquipments200Response
     */
    'data': Array<GetMusclesGet200ResponseDataInner>;
}
/**
 * 
 * @export
 * @interface GetExerciseById200Response
 */
export interface GetExerciseById200Response {
    /**
     * Indicates whether the request was successful.
     * @type {boolean}
     * @memberof GetExerciseById200Response
     */
    'success': boolean;
    /**
     * 
     * @type {GetExerciseById200ResponseData}
     * @memberof GetExerciseById200Response
     */
    'data': GetExerciseById200ResponseData;
}
/**
 * The retrieved exercise details.
 * @export
 * @interface GetExerciseById200ResponseData
 */
export interface GetExerciseById200ResponseData {
    /**
     * 
     * @type {string}
     * @memberof GetExerciseById200ResponseData
     */
    'exerciseId': string;
    /**
     * 
     * @type {string}
     * @memberof GetExerciseById200ResponseData
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof GetExerciseById200ResponseData
     */
    'gifUrl': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetExerciseById200ResponseData
     */
    'targetMuscles': Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetExerciseById200ResponseData
     */
    'bodyParts': Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetExerciseById200ResponseData
     */
    'equipments': Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetExerciseById200ResponseData
     */
    'secondaryMuscles': Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetExerciseById200ResponseData
     */
    'instructions': Array<string>;
}
/**
 * 
 * @export
 * @interface GetExercises200Response
 */
export interface GetExercises200Response {
    /**
     * Indicates whether the request was successful
     * @type {boolean}
     * @memberof GetExercises200Response
     */
    'success': boolean;
    /**
     * Array of Exercises.
     * @type {Array<GetExercises200ResponseDataInner>}
     * @memberof GetExercises200Response
     */
    'data': Array<GetExercises200ResponseDataInner>;
}
/**
 * 
 * @export
 * @interface GetExercises200ResponseDataInner
 */
export interface GetExercises200ResponseDataInner {
    /**
     * 
     * @type {string}
     * @memberof GetExercises200ResponseDataInner
     */
    'exerciseId': string;
    /**
     * 
     * @type {string}
     * @memberof GetExercises200ResponseDataInner
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof GetExercises200ResponseDataInner
     */
    'gifUrl': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetExercises200ResponseDataInner
     */
    'targetMuscles': Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetExercises200ResponseDataInner
     */
    'bodyParts': Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetExercises200ResponseDataInner
     */
    'equipments': Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetExercises200ResponseDataInner
     */
    'secondaryMuscles': Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetExercises200ResponseDataInner
     */
    'instructions': Array<string>;
}
/**
 * 
 * @export
 * @interface GetMusclesGet200Response
 */
export interface GetMusclesGet200Response {
    /**
     * Indicates whether the request was successful
     * @type {boolean}
     * @memberof GetMusclesGet200Response
     */
    'success': boolean;
    /**
     * Array of Muslces.
     * @type {Array<GetMusclesGet200ResponseDataInner>}
     * @memberof GetMusclesGet200Response
     */
    'data': Array<GetMusclesGet200ResponseDataInner>;
}
/**
 * 
 * @export
 * @interface GetMusclesGet200ResponseDataInner
 */
export interface GetMusclesGet200ResponseDataInner {
    /**
     * 
     * @type {string}
     * @memberof GetMusclesGet200ResponseDataInner
     */
    'name': string;
}
/**
 * 
 * @export
 * @interface RegisterUser201Response
 */
export interface RegisterUser201Response {
    /**
     * Indicates whether the request was successful
     * @type {boolean}
     * @memberof RegisterUser201Response
     */
    'success': boolean;
    /**
     * 
     * @type {UserData}
     * @memberof RegisterUser201Response
     */
    'data': UserData;
}
/**
 * 
 * @export
 * @interface RegisterUserRequest
 */
export interface RegisterUserRequest {
    /**
     * Email for account register
     * @type {string}
     * @memberof RegisterUserRequest
     */
    'email': string;
}
/**
 * 
 * @export
 * @interface UploadGifImage201Response
 */
export interface UploadGifImage201Response {
    /**
     * Indicates whether the upload was successful
     * @type {boolean}
     * @memberof UploadGifImage201Response
     */
    'success': boolean;
    /**
     * 
     * @type {UploadedImageData}
     * @memberof UploadGifImage201Response
     */
    'data': UploadedImageData;
}
/**
 * Details of the uploaded GIF image
 * @export
 * @interface UploadedImageData
 */
export interface UploadedImageData {
    /**
     * The URL where the uploaded GIF image can be accessed
     * @type {string}
     * @memberof UploadedImageData
     */
    'publicUrl': string;
}
/**
 * The newly registered user
 * @export
 * @interface UserData
 */
export interface UserData {
    /**
     * user unique identifier
     * @type {string}
     * @memberof UserData
     */
    'id': string;
    /**
     * user email address
     * @type {string}
     * @memberof UserData
     */
    'email': string;
    /**
     * user active role
     * @type {string}
     * @memberof UserData
     */
    'role': string;
    /**
     * user account activation status
     * @type {string}
     * @memberof UserData
     */
    'isActivated': string;
    /**
     * otp secret for adding in authenticator app
     * @type {string}
     * @memberof UserData
     */
    'otpSecret': string;
}

/**
 * BodyPartsApi - axios parameter creator
 * @export
 */
export const BodyPartsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * This route is used to add a new bodyPart name to the database.
         * @summary Add a new bodyPart to the database
         * @param {CreatebodyPartRequest} [createbodyPartRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createbodyPart: async (createbodyPartRequest?: CreatebodyPartRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/bodyparts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createbodyPartRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrive list of all bodyparts.
         * @summary Retrive all bodyParts.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBodyParts: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/bodyparts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrive list of all bodyparts.
         * @summary Retrive exercises by bodyPart
         * @param {string} bodyPartName 
         * @param {number} [offset] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getExercisesByBodyPart: async (bodyPartName: string, offset?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'bodyPartName' is not null or undefined
            assertParamExists('getExercisesByBodyPart', 'bodyPartName', bodyPartName)
            const localVarPath = `/api/v1/bodyparts/{bodyPartName}/exercises`
                .replace(`{${"bodyPartName"}}`, encodeURIComponent(String(bodyPartName)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BodyPartsApi - functional programming interface
 * @export
 */
export const BodyPartsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BodyPartsApiAxiosParamCreator(configuration)
    return {
        /**
         * This route is used to add a new bodyPart name to the database.
         * @summary Add a new bodyPart to the database
         * @param {CreatebodyPartRequest} [createbodyPartRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createbodyPart(createbodyPartRequest?: CreatebodyPartRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreatebodyPart201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createbodyPart(createbodyPartRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BodyPartsApi.createbodyPart']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrive list of all bodyparts.
         * @summary Retrive all bodyParts.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBodyParts(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetBodyParts200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getBodyParts(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BodyPartsApi.getBodyParts']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrive list of all bodyparts.
         * @summary Retrive exercises by bodyPart
         * @param {string} bodyPartName 
         * @param {number} [offset] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getExercisesByBodyPart(bodyPartName: string, offset?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetExercises200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getExercisesByBodyPart(bodyPartName, offset, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BodyPartsApi.getExercisesByBodyPart']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * BodyPartsApi - factory interface
 * @export
 */
export const BodyPartsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BodyPartsApiFp(configuration)
    return {
        /**
         * This route is used to add a new bodyPart name to the database.
         * @summary Add a new bodyPart to the database
         * @param {CreatebodyPartRequest} [createbodyPartRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createbodyPart(createbodyPartRequest?: CreatebodyPartRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreatebodyPart201Response> {
            return localVarFp.createbodyPart(createbodyPartRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrive list of all bodyparts.
         * @summary Retrive all bodyParts.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBodyParts(options?: RawAxiosRequestConfig): AxiosPromise<GetBodyParts200Response> {
            return localVarFp.getBodyParts(options).then((request) => request(axios, basePath));
        },
        /**
         * Retrive list of all bodyparts.
         * @summary Retrive exercises by bodyPart
         * @param {string} bodyPartName 
         * @param {number} [offset] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getExercisesByBodyPart(bodyPartName: string, offset?: number, limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<GetExercises200Response> {
            return localVarFp.getExercisesByBodyPart(bodyPartName, offset, limit, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * BodyPartsApi - object-oriented interface
 * @export
 * @class BodyPartsApi
 * @extends {BaseAPI}
 */
export class BodyPartsApi extends BaseAPI {
    /**
     * This route is used to add a new bodyPart name to the database.
     * @summary Add a new bodyPart to the database
     * @param {CreatebodyPartRequest} [createbodyPartRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BodyPartsApi
     */
    public createbodyPart(createbodyPartRequest?: CreatebodyPartRequest, options?: RawAxiosRequestConfig) {
        return BodyPartsApiFp(this.configuration).createbodyPart(createbodyPartRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrive list of all bodyparts.
     * @summary Retrive all bodyParts.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BodyPartsApi
     */
    public getBodyParts(options?: RawAxiosRequestConfig) {
        return BodyPartsApiFp(this.configuration).getBodyParts(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrive list of all bodyparts.
     * @summary Retrive exercises by bodyPart
     * @param {string} bodyPartName 
     * @param {number} [offset] 
     * @param {number} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BodyPartsApi
     */
    public getExercisesByBodyPart(bodyPartName: string, offset?: number, limit?: number, options?: RawAxiosRequestConfig) {
        return BodyPartsApiFp(this.configuration).getExercisesByBodyPart(bodyPartName, offset, limit, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * EquipmentsApi - axios parameter creator
 * @export
 */
export const EquipmentsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * This route is used to add a new equipment name to the database.
         * @summary Add a new equipment to the database
         * @param {CreateEquipmentRequest} [createEquipmentRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createEquipment: async (createEquipmentRequest?: CreateEquipmentRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/equipments`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createEquipmentRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrive list of all equipments.
         * @summary Retrive all equipments.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEquipments: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/equipments`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrive list of all equipments.
         * @summary Retrive exercises by equipments
         * @param {string} equipmentName 
         * @param {number} [offset] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getExercisesByAnEquipment: async (equipmentName: string, offset?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'equipmentName' is not null or undefined
            assertParamExists('getExercisesByAnEquipment', 'equipmentName', equipmentName)
            const localVarPath = `/api/v1/equipments/{equipmentName}/exercises`
                .replace(`{${"equipmentName"}}`, encodeURIComponent(String(equipmentName)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EquipmentsApi - functional programming interface
 * @export
 */
export const EquipmentsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EquipmentsApiAxiosParamCreator(configuration)
    return {
        /**
         * This route is used to add a new equipment name to the database.
         * @summary Add a new equipment to the database
         * @param {CreateEquipmentRequest} [createEquipmentRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createEquipment(createEquipmentRequest?: CreateEquipmentRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateEquipment201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createEquipment(createEquipmentRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EquipmentsApi.createEquipment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrive list of all equipments.
         * @summary Retrive all equipments.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getEquipments(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetEquipments200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getEquipments(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EquipmentsApi.getEquipments']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrive list of all equipments.
         * @summary Retrive exercises by equipments
         * @param {string} equipmentName 
         * @param {number} [offset] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getExercisesByAnEquipment(equipmentName: string, offset?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetExercises200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getExercisesByAnEquipment(equipmentName, offset, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EquipmentsApi.getExercisesByAnEquipment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * EquipmentsApi - factory interface
 * @export
 */
export const EquipmentsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EquipmentsApiFp(configuration)
    return {
        /**
         * This route is used to add a new equipment name to the database.
         * @summary Add a new equipment to the database
         * @param {CreateEquipmentRequest} [createEquipmentRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createEquipment(createEquipmentRequest?: CreateEquipmentRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateEquipment201Response> {
            return localVarFp.createEquipment(createEquipmentRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrive list of all equipments.
         * @summary Retrive all equipments.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEquipments(options?: RawAxiosRequestConfig): AxiosPromise<GetEquipments200Response> {
            return localVarFp.getEquipments(options).then((request) => request(axios, basePath));
        },
        /**
         * Retrive list of all equipments.
         * @summary Retrive exercises by equipments
         * @param {string} equipmentName 
         * @param {number} [offset] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getExercisesByAnEquipment(equipmentName: string, offset?: number, limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<GetExercises200Response> {
            return localVarFp.getExercisesByAnEquipment(equipmentName, offset, limit, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * EquipmentsApi - object-oriented interface
 * @export
 * @class EquipmentsApi
 * @extends {BaseAPI}
 */
export class EquipmentsApi extends BaseAPI {
    /**
     * This route is used to add a new equipment name to the database.
     * @summary Add a new equipment to the database
     * @param {CreateEquipmentRequest} [createEquipmentRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EquipmentsApi
     */
    public createEquipment(createEquipmentRequest?: CreateEquipmentRequest, options?: RawAxiosRequestConfig) {
        return EquipmentsApiFp(this.configuration).createEquipment(createEquipmentRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrive list of all equipments.
     * @summary Retrive all equipments.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EquipmentsApi
     */
    public getEquipments(options?: RawAxiosRequestConfig) {
        return EquipmentsApiFp(this.configuration).getEquipments(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrive list of all equipments.
     * @summary Retrive exercises by equipments
     * @param {string} equipmentName 
     * @param {number} [offset] 
     * @param {number} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EquipmentsApi
     */
    public getExercisesByAnEquipment(equipmentName: string, offset?: number, limit?: number, options?: RawAxiosRequestConfig) {
        return EquipmentsApiFp(this.configuration).getExercisesByAnEquipment(equipmentName, offset, limit, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ExercisesApi - axios parameter creator
 * @export
 */
export const ExercisesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieves a list of exercise names that match the search term using fuzzy search. This endpoint provides autocomplete suggestions based on the MongoDB autocomplete feature, helping users find exercises quickly as they type.
         * @summary Autocomplete Exercise Search
         * @param {string} [search] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        autocompleteExercises: async (search?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/exercises/autocomplete`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This route is used to add a new exercises to database.
         * @summary Add a new exercises to the database
         * @param {CreateExerciseRequest} [createExerciseRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createExercise: async (createExerciseRequest?: CreateExerciseRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/exercises`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createExerciseRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves a specific exercise by its unique identifier.
         * @summary Get exercise by ID
         * @param {string} exerciseId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getExerciseById: async (exerciseId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'exerciseId' is not null or undefined
            assertParamExists('getExerciseById', 'exerciseId', exerciseId)
            const localVarPath = `/api/v1/exercises/{exerciseId}`
                .replace(`{${"exerciseId"}}`, encodeURIComponent(String(exerciseId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrive list of all the exercises.
         * @summary Retrive all exercises.
         * @param {string} [search] 
         * @param {number} [offset] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getExercises: async (search?: string, offset?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/exercises`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ExercisesApi - functional programming interface
 * @export
 */
export const ExercisesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ExercisesApiAxiosParamCreator(configuration)
    return {
        /**
         * Retrieves a list of exercise names that match the search term using fuzzy search. This endpoint provides autocomplete suggestions based on the MongoDB autocomplete feature, helping users find exercises quickly as they type.
         * @summary Autocomplete Exercise Search
         * @param {string} [search] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async autocompleteExercises(search?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AutocompleteExercises200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.autocompleteExercises(search, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExercisesApi.autocompleteExercises']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * This route is used to add a new exercises to database.
         * @summary Add a new exercises to the database
         * @param {CreateExerciseRequest} [createExerciseRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createExercise(createExerciseRequest?: CreateExerciseRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateExercise201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createExercise(createExerciseRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExercisesApi.createExercise']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieves a specific exercise by its unique identifier.
         * @summary Get exercise by ID
         * @param {string} exerciseId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getExerciseById(exerciseId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetExerciseById200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getExerciseById(exerciseId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExercisesApi.getExerciseById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrive list of all the exercises.
         * @summary Retrive all exercises.
         * @param {string} [search] 
         * @param {number} [offset] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getExercises(search?: string, offset?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetExercises200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getExercises(search, offset, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExercisesApi.getExercises']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ExercisesApi - factory interface
 * @export
 */
export const ExercisesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ExercisesApiFp(configuration)
    return {
        /**
         * Retrieves a list of exercise names that match the search term using fuzzy search. This endpoint provides autocomplete suggestions based on the MongoDB autocomplete feature, helping users find exercises quickly as they type.
         * @summary Autocomplete Exercise Search
         * @param {string} [search] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        autocompleteExercises(search?: string, options?: RawAxiosRequestConfig): AxiosPromise<AutocompleteExercises200Response> {
            return localVarFp.autocompleteExercises(search, options).then((request) => request(axios, basePath));
        },
        /**
         * This route is used to add a new exercises to database.
         * @summary Add a new exercises to the database
         * @param {CreateExerciseRequest} [createExerciseRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createExercise(createExerciseRequest?: CreateExerciseRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateExercise201Response> {
            return localVarFp.createExercise(createExerciseRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves a specific exercise by its unique identifier.
         * @summary Get exercise by ID
         * @param {string} exerciseId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getExerciseById(exerciseId: string, options?: RawAxiosRequestConfig): AxiosPromise<GetExerciseById200Response> {
            return localVarFp.getExerciseById(exerciseId, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrive list of all the exercises.
         * @summary Retrive all exercises.
         * @param {string} [search] 
         * @param {number} [offset] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getExercises(search?: string, offset?: number, limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<GetExercises200Response> {
            return localVarFp.getExercises(search, offset, limit, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ExercisesApi - object-oriented interface
 * @export
 * @class ExercisesApi
 * @extends {BaseAPI}
 */
export class ExercisesApi extends BaseAPI {
    /**
     * Retrieves a list of exercise names that match the search term using fuzzy search. This endpoint provides autocomplete suggestions based on the MongoDB autocomplete feature, helping users find exercises quickly as they type.
     * @summary Autocomplete Exercise Search
     * @param {string} [search] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExercisesApi
     */
    public autocompleteExercises(search?: string, options?: RawAxiosRequestConfig) {
        return ExercisesApiFp(this.configuration).autocompleteExercises(search, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This route is used to add a new exercises to database.
     * @summary Add a new exercises to the database
     * @param {CreateExerciseRequest} [createExerciseRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExercisesApi
     */
    public createExercise(createExerciseRequest?: CreateExerciseRequest, options?: RawAxiosRequestConfig) {
        return ExercisesApiFp(this.configuration).createExercise(createExerciseRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves a specific exercise by its unique identifier.
     * @summary Get exercise by ID
     * @param {string} exerciseId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExercisesApi
     */
    public getExerciseById(exerciseId: string, options?: RawAxiosRequestConfig) {
        return ExercisesApiFp(this.configuration).getExerciseById(exerciseId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrive list of all the exercises.
     * @summary Retrive all exercises.
     * @param {string} [search] 
     * @param {number} [offset] 
     * @param {number} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExercisesApi
     */
    public getExercises(search?: string, offset?: number, limit?: number, options?: RawAxiosRequestConfig) {
        return ExercisesApiFp(this.configuration).getExercises(search, offset, limit, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ImagesApi - axios parameter creator
 * @export
 */
export const ImagesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * This route allows users to upload a GIF image file.
         * @summary Upload a GIF image
         * @param {File} [file] The GIF image file to be uploaded
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadGifImage: async (file?: File, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/images/upload`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();


            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This route allows users to view a GIF image by its name.
         * @summary View a GIF image
         * @param {string} imageName 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        viewGifImage: async (imageName: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'imageName' is not null or undefined
            assertParamExists('viewGifImage', 'imageName', imageName)
            const localVarPath = `/api/v1/images/{imageName}`
                .replace(`{${"imageName"}}`, encodeURIComponent(String(imageName)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ImagesApi - functional programming interface
 * @export
 */
export const ImagesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ImagesApiAxiosParamCreator(configuration)
    return {
        /**
         * This route allows users to upload a GIF image file.
         * @summary Upload a GIF image
         * @param {File} [file] The GIF image file to be uploaded
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadGifImage(file?: File, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UploadGifImage201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.uploadGifImage(file, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ImagesApi.uploadGifImage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * This route allows users to view a GIF image by its name.
         * @summary View a GIF image
         * @param {string} imageName 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async viewGifImage(imageName: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.viewGifImage(imageName, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ImagesApi.viewGifImage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ImagesApi - factory interface
 * @export
 */
export const ImagesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ImagesApiFp(configuration)
    return {
        /**
         * This route allows users to upload a GIF image file.
         * @summary Upload a GIF image
         * @param {File} [file] The GIF image file to be uploaded
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadGifImage(file?: File, options?: RawAxiosRequestConfig): AxiosPromise<UploadGifImage201Response> {
            return localVarFp.uploadGifImage(file, options).then((request) => request(axios, basePath));
        },
        /**
         * This route allows users to view a GIF image by its name.
         * @summary View a GIF image
         * @param {string} imageName 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        viewGifImage(imageName: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.viewGifImage(imageName, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ImagesApi - object-oriented interface
 * @export
 * @class ImagesApi
 * @extends {BaseAPI}
 */
export class ImagesApi extends BaseAPI {
    /**
     * This route allows users to upload a GIF image file.
     * @summary Upload a GIF image
     * @param {File} [file] The GIF image file to be uploaded
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ImagesApi
     */
    public uploadGifImage(file?: File, options?: RawAxiosRequestConfig) {
        return ImagesApiFp(this.configuration).uploadGifImage(file, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This route allows users to view a GIF image by its name.
     * @summary View a GIF image
     * @param {string} imageName 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ImagesApi
     */
    public viewGifImage(imageName: string, options?: RawAxiosRequestConfig) {
        return ImagesApiFp(this.configuration).viewGifImage(imageName, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * MusclesApi - axios parameter creator
 * @export
 */
export const MusclesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * This route is used to add a new muscle name to the database.
         * @summary Add a new muscle to the database
         * @param {CreateMuscleRequest} [createMuscleRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createMuscle: async (createMuscleRequest?: CreateMuscleRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/muscles`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createMuscleRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrive list of exercises by targetMuscles or secondaryMuscles.
         * @summary Retrive exercises by muscles
         * @param {string} muscleName 
         * @param {number} [offset] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getExercisesByEquipment: async (muscleName: string, offset?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'muscleName' is not null or undefined
            assertParamExists('getExercisesByEquipment', 'muscleName', muscleName)
            const localVarPath = `/api/v1/muscles/{muscleName}/exercises`
                .replace(`{${"muscleName"}}`, encodeURIComponent(String(muscleName)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrive list of all the muscles.
         * @summary Retrive all muscles.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMusclesGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/muscles`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MusclesApi - functional programming interface
 * @export
 */
export const MusclesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MusclesApiAxiosParamCreator(configuration)
    return {
        /**
         * This route is used to add a new muscle name to the database.
         * @summary Add a new muscle to the database
         * @param {CreateMuscleRequest} [createMuscleRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createMuscle(createMuscleRequest?: CreateMuscleRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateMuscle201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createMuscle(createMuscleRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MusclesApi.createMuscle']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrive list of exercises by targetMuscles or secondaryMuscles.
         * @summary Retrive exercises by muscles
         * @param {string} muscleName 
         * @param {number} [offset] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getExercisesByEquipment(muscleName: string, offset?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetExercises200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getExercisesByEquipment(muscleName, offset, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MusclesApi.getExercisesByEquipment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrive list of all the muscles.
         * @summary Retrive all muscles.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMusclesGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetMusclesGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMusclesGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MusclesApi.getMusclesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MusclesApi - factory interface
 * @export
 */
export const MusclesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MusclesApiFp(configuration)
    return {
        /**
         * This route is used to add a new muscle name to the database.
         * @summary Add a new muscle to the database
         * @param {CreateMuscleRequest} [createMuscleRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createMuscle(createMuscleRequest?: CreateMuscleRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateMuscle201Response> {
            return localVarFp.createMuscle(createMuscleRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrive list of exercises by targetMuscles or secondaryMuscles.
         * @summary Retrive exercises by muscles
         * @param {string} muscleName 
         * @param {number} [offset] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getExercisesByEquipment(muscleName: string, offset?: number, limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<GetExercises200Response> {
            return localVarFp.getExercisesByEquipment(muscleName, offset, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrive list of all the muscles.
         * @summary Retrive all muscles.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMusclesGet(options?: RawAxiosRequestConfig): AxiosPromise<GetMusclesGet200Response> {
            return localVarFp.getMusclesGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MusclesApi - object-oriented interface
 * @export
 * @class MusclesApi
 * @extends {BaseAPI}
 */
export class MusclesApi extends BaseAPI {
    /**
     * This route is used to add a new muscle name to the database.
     * @summary Add a new muscle to the database
     * @param {CreateMuscleRequest} [createMuscleRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MusclesApi
     */
    public createMuscle(createMuscleRequest?: CreateMuscleRequest, options?: RawAxiosRequestConfig) {
        return MusclesApiFp(this.configuration).createMuscle(createMuscleRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrive list of exercises by targetMuscles or secondaryMuscles.
     * @summary Retrive exercises by muscles
     * @param {string} muscleName 
     * @param {number} [offset] 
     * @param {number} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MusclesApi
     */
    public getExercisesByEquipment(muscleName: string, offset?: number, limit?: number, options?: RawAxiosRequestConfig) {
        return MusclesApiFp(this.configuration).getExercisesByEquipment(muscleName, offset, limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrive list of all the muscles.
     * @summary Retrive all muscles.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MusclesApi
     */
    public getMusclesGet(options?: RawAxiosRequestConfig) {
        return MusclesApiFp(this.configuration).getMusclesGet(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UsersApi - axios parameter creator
 * @export
 */
export const UsersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * This route is used to authenticate user based on email and authenticator code.
         * @summary User Authentication
         * @param {AuthenticateUserRequest} [authenticateUserRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authenticateUser: async (authenticateUserRequest?: AuthenticateUserRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/authenticate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(authenticateUserRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This route is used to register user account.
         * @summary register users endpoint 
         * @param {RegisterUserRequest} [registerUserRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerUser: async (registerUserRequest?: RegisterUserRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(registerUserRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UsersApi - functional programming interface
 * @export
 */
export const UsersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UsersApiAxiosParamCreator(configuration)
    return {
        /**
         * This route is used to authenticate user based on email and authenticator code.
         * @summary User Authentication
         * @param {AuthenticateUserRequest} [authenticateUserRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authenticateUser(authenticateUserRequest?: AuthenticateUserRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthenticateUser200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authenticateUser(authenticateUserRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.authenticateUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * This route is used to register user account.
         * @summary register users endpoint 
         * @param {RegisterUserRequest} [registerUserRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async registerUser(registerUserRequest?: RegisterUserRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RegisterUser201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.registerUser(registerUserRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.registerUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UsersApi - factory interface
 * @export
 */
export const UsersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UsersApiFp(configuration)
    return {
        /**
         * This route is used to authenticate user based on email and authenticator code.
         * @summary User Authentication
         * @param {AuthenticateUserRequest} [authenticateUserRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authenticateUser(authenticateUserRequest?: AuthenticateUserRequest, options?: RawAxiosRequestConfig): AxiosPromise<AuthenticateUser200Response> {
            return localVarFp.authenticateUser(authenticateUserRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * This route is used to register user account.
         * @summary register users endpoint 
         * @param {RegisterUserRequest} [registerUserRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerUser(registerUserRequest?: RegisterUserRequest, options?: RawAxiosRequestConfig): AxiosPromise<RegisterUser201Response> {
            return localVarFp.registerUser(registerUserRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UsersApi - object-oriented interface
 * @export
 * @class UsersApi
 * @extends {BaseAPI}
 */
export class UsersApi extends BaseAPI {
    /**
     * This route is used to authenticate user based on email and authenticator code.
     * @summary User Authentication
     * @param {AuthenticateUserRequest} [authenticateUserRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public authenticateUser(authenticateUserRequest?: AuthenticateUserRequest, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).authenticateUser(authenticateUserRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This route is used to register user account.
     * @summary register users endpoint 
     * @param {RegisterUserRequest} [registerUserRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public registerUser(registerUserRequest?: RegisterUserRequest, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).registerUser(registerUserRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



