/* tslint:disable */
/* eslint-disable */
/**
 * ExerciseDB API
 * # Introduction             ExerciseDB API, accessible at [exercisedb-api.vercel.app](https://exercisedb-api.vercel.app), is an exercises API that allows users to access high-quality exercises data which consists 1300+ exercises.           This API offers extensive information on each exercise, including target body parts, equipment needed, GIFs for visual guidance, and step-by-step instructions. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

